apiVersion: batch/v1
kind: Job
metadata:
  name: submission-parallel
spec:
  template:
    spec:
      serviceAccountName: submission-worker
      nodeSelector:
        node.kubernetes.io/instance-type: g5.12xlarge

      initContainers:
        - name: private-contents
          image: 342236305043.dkr.ecr.us-east-1.amazonaws.com/leaderboard-testing
          command: ["/bin/bash", "-c"]
          args:
            - |
              cp -r ${LEADERBOARD_ROOT}/* /tmp/leaderboard/
              cp -r ${SCENARIO_RUNNER_ROOT}/* /tmp/scenario_runner/
              cp -r ${CARLA_PYTHON_API_ROOT}/* /tmp/CARLA/

              mkdir -m 0777 -p /tmp/logs/agent{1..4}
              mkdir -m 0777 -p /tmp/logs/simulator
          volumeMounts:
            - mountPath: /tmp/leaderboard
              name: leaderboard
            - mountPath: /tmp/scenario_runner
              name: scenario-runner
            - mountPath: /tmp/CARLA
              name: carla-python-api
            - mountPath: /tmp/logs
              name: logs

      containers:
        # First set of simulator + agent
        - name: simulator-1
          image: 342236305043.dkr.ecr.us-east-1.amazonaws.com/challenge-simulator:latest
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Starting CARLA server"
              ./CarlaUE4.sh  -carla-rpc-port=${CARLA_PORT} -opengl -nosound
              echo "Stopped CARLA server"
              exit 0
          env:
            - name: CARLA_PORT
              value: "2000"
            - name: OMP_PROC_BIND
              value: "FALSE"
            - name: OMP_NUM_THREADS
              value: "64"
            - name: SDL_VIDEODRIVER
              value: "offscreen"
            - name: NVIDIA_VISIBLE_DEVICES
              value: "0"
          volumeMounts:
            - mountPath: /home/carla/CarlaUE4/Saved
              name: logs
              subPath: simulator
          securityContext:
            privileged: true
          resources:
            limits:
              nvidia.com/gpu: 1
        - name: agent-1
          image: 342236305043.dkr.ecr.us-east-1.amazonaws.com/bm-586a194d-team-403:efac48dd-abc1-47e2-bd3b-89c036b5faeb
          command: ["/bin/bash", "-c"]
          args:
            - |
              bash /workspace/leaderboard/run_leaderboard.sh
          volumeMounts:
            - mountPath: /workspace/leaderboard
              name: leaderboard
            - mountPath: /workspace/scenario_runner
              name: scenario-runner
            - mountPath: /workspace/CARLA
              name: carla-python-api
            - mountPath: /tmp/agent
              name: logs
              subPath: agent1
          env:
            - name: CARLA_PORT
              value: "2000"
            - name: CHALLENGE_TRACK_CODENAME
              value: "SENSORS"
            - name: ROUTES_SUBSET
              value: "0-4"
            - name: RESUME
              value: ""
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "all"
            - name: NVIDIA_VISIBLE_DEVICES
              value: "0"

        # Second set of simulator + agent
        - name: simulator-2
          image: 342236305043.dkr.ecr.us-east-1.amazonaws.com/challenge-simulator:latest
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Starting CARLA server"
              ./CarlaUE4.sh  -carla-rpc-port=${CARLA_PORT} -opengl -nosound
              echo "Stopped CARLA server"
              exit 0
          env:
            - name: CARLA_PORT
              value: "2100"
            - name: OMP_PROC_BIND
              value: "FALSE"
            - name: OMP_NUM_THREADS
              value: "64"
            - name: SDL_VIDEODRIVER
              value: "offscreen"
            - name: NVIDIA_VISIBLE_DEVICES
              value: "1"
          volumeMounts:
            - mountPath: /home/carla/CarlaUE4/Saved
              name: logs
              subPath: simulator
          securityContext:
            privileged: true
          resources:
            limits:
              nvidia.com/gpu: 1
        - name: agent-2
          image: 342236305043.dkr.ecr.us-east-1.amazonaws.com/bm-586a194d-team-403:efac48dd-abc1-47e2-bd3b-89c036b5faeb
          command: ["/bin/bash", "-c"]
          args:
            - |
              bash /workspace/leaderboard/run_leaderboard.sh 
          volumeMounts:
            - mountPath: /workspace/leaderboard
              name: leaderboard
            - mountPath: /workspace/scenario_runner
              name: scenario-runner
            - mountPath: /workspace/CARLA
              name: carla-python-api
            - mountPath: /tmp/agent
              name: logs
              subPath: agent2
          env:
            - name: CARLA_PORT
              value: "2100"
            - name: CHALLENGE_TRACK_CODENAME
              value: "SENSORS"
            - name: ROUTES_SUBSET
              value: "5-9"
            - name: RESUME
              value: ""
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "all"
            - name: NVIDIA_VISIBLE_DEVICES
              value: "1"

        # Third set of simulator + agent
        - name: simulator-3
          image: 342236305043.dkr.ecr.us-east-1.amazonaws.com/challenge-simulator:latest
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Starting CARLA server"
              ./CarlaUE4.sh  -carla-rpc-port=${CARLA_PORT} -opengl -nosound
              echo "Stopped CARLA server"
              exit 0
          env:
            - name: CARLA_PORT
              value: "2200"
            - name: OMP_PROC_BIND
              value: "FALSE"
            - name: OMP_NUM_THREADS
              value: "64"
            - name: SDL_VIDEODRIVER
              value: "offscreen"
            - name: NVIDIA_VISIBLE_DEVICES
              value: "2"
          volumeMounts:
            - mountPath: /home/carla/CarlaUE4/Saved
              name: logs
              subPath: simulator
          securityContext:
            privileged: true
          resources:
            limits:
              nvidia.com/gpu: 1
        - name: agent-3
          image: 342236305043.dkr.ecr.us-east-1.amazonaws.com/bm-586a194d-team-403:efac48dd-abc1-47e2-bd3b-89c036b5faeb
          command: ["/bin/bash", "-c"]
          args:
            - |
              bash /workspace/leaderboard/run_leaderboard.sh 
          volumeMounts:
            - mountPath: /workspace/leaderboard
              name: leaderboard
            - mountPath: /workspace/scenario_runner
              name: scenario-runner
            - mountPath: /workspace/CARLA
              name: carla-python-api
            - mountPath: /tmp/agent
              name: logs
              subPath: agent3
          env:
            - name: CARLA_PORT
              value: "2200"
            - name: CHALLENGE_TRACK_CODENAME
              value: "SENSORS"
            - name: ROUTES_SUBSET
              value: "10-14"
            - name: RESUME
              value: ""
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "all"
            - name: NVIDIA_VISIBLE_DEVICES
              value: "2"

        # Four set of simulator + agent
        - name: simulator-4
          image: 342236305043.dkr.ecr.us-east-1.amazonaws.com/challenge-simulator:latest
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Starting CARLA server"
              ./CarlaUE4.sh  -carla-rpc-port=${CARLA_PORT} -opengl -nosound
              echo "Stopped CARLA server"
              exit 0
          env:
            - name: CARLA_PORT
              value: "2300"
            - name: OMP_PROC_BIND
              value: "FALSE"
            - name: OMP_NUM_THREADS
              value: "64"
            - name: SDL_VIDEODRIVER
              value: "offscreen"
            - name: NVIDIA_VISIBLE_DEVICES
              value: "3"
          volumeMounts:
            - mountPath: /home/carla/CarlaUE4/Saved
              name: logs
              subPath: simulator
          securityContext:
            privileged: true
          resources:
            limits:
              nvidia.com/gpu: 1
        - name: agent-4
          image: 342236305043.dkr.ecr.us-east-1.amazonaws.com/bm-586a194d-team-403:efac48dd-abc1-47e2-bd3b-89c036b5faeb
          command: ["/bin/bash", "-c"]
          args:
            - |
              bash /workspace/leaderboard/run_leaderboard.sh
          volumeMounts:
            - mountPath: /workspace/leaderboard
              name: leaderboard
            - mountPath: /workspace/scenario_runner
              name: scenario-runner
            - mountPath: /workspace/CARLA
              name: carla-python-api
            - mountPath: /tmp/agent
              name: logs
              subPath: agent4
          env:
            - name: CARLA_PORT
              value: "2300"
            - name: CHALLENGE_TRACK_CODENAME
              value: "SENSORS"
            - name: ROUTES_SUBSET
              value: "15-19"
            - name: RESUME
              value: ""
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "all"
            - name: NVIDIA_VISIBLE_DEVICES
              value: "3"

        # Log copy container
        - name: logcopy
          image: 342236305043.dkr.ecr.us-east-1.amazonaws.com/leaderboard-20-logcopy:latest
          command: ["/bin/bash", "-c"]
          args:
            - |
              bash /workspace/run_logcopy.sh
          env:
            - name: SUBMISSION_ID
              value: leaderboard-10-test-1
          volumeMounts:
            - mountPath: /logs
              name: logs
            - mountPath: /utils/leaderboard
              name: leaderboard
            - mountPath: /utils/scenario_runner
              name: scenario-runner

      restartPolicy: Never
      volumes:
        - name: leaderboard
          emptyDir: {}
        - name: scenario-runner
          emptyDir: {}
        - name: carla-python-api
          emptyDir: {}
        - name: logs
          emptyDir: {}

  backoffLimit: 0
