apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: beta-leaderboard-20
  region: us-east-2
  version: "1.24"

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: fluentd
      namespace: kube-system
    attachPolicy:
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "logs:CreateLogStream"
        - "logs:CreateLogGroup"
        - "logs:PutLogEvents"
        - "logs:DescribeLogGroups"
        - "logs:DescribeLogStreams"
        Resource: "arn:aws:logs:*:*:*"
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
    wellKnownPolicies:
      autoScaler: true
  - metadata:
      name: submission-worker
    attachPolicy:
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        # AWSAppRunnerServicePolicyForECRAccess
        - "ecr:GetDownloadUrlForLayer"
        - "ecr:BatchGetImage"
        - "ecr:DescribeImages"
        - "ecr:GetAuthorizationToken"
        - "ecr:BatchCheckLayerAvailability"
        # AWSS3FullAccess
        - "s3:*"
        - "s3-object-lambda:*"
        Resource:
        #- "arn:aws:s3:::"arn:aws:s3:::carla-leaderboard-20-logs"
        - "arn:aws:ecr:*:342236305043:repository/*"

nodeGroups:
  - name: autoscaler-worker
    amiFamily: AmazonLinux2
    instanceType: t3.large
    desiredCapacity: 1
    volumeSize: 100
    labels:
      nodegroup-type: non-gpu
  - name: submission-worker
    instanceType: g4dn.2xlarge
    amiFamily: Ubuntu2004
    ami: ami-055cd5e1dec7dabb7
    desiredCapacity: 0
    minSize: 0
    maxSize: 10
    volumeSize: 400
    tags:
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/beta-leaderboard-20: "owned"
    labels:
      nodegroup-type: gpu-instances
      autoscaling: enabled
      purpose: gpu-worker
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh beta-leaderboard-20
    preBootstrapCommands:
      - "grep --quiet tsc /sys/devices/system/clocksource/clocksource0/available_clocksource && sudo bash -c 'echo tsc > /sys/devices/system/clocksource/clocksource0/current_clocksource'"
      - "sudo sh -c \"cat /etc/docker/daemon.json | jq '. += {\\\"default-runtime\\\": \\\"nvidia\\\", \\\"runtimes\\\": {\\\"nvidia\\\": {\\\"path\\\": \\\"/usr/bin/nvidia-container-runtime\\\", \\\"runtimeArgs\\\": []}}}' | tee /etc/docker/daemon.json\""
      - "sudo nvidia-xconfig --preserve-busid -a --virtual=1280x1024"
      - "sudo X :0&"
