apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: evalai-test
  region: us-east-2
  version: "1.24"

nodeGroups:
  - name: basic
    amiFamily: AmazonLinux2
    instanceType: t3.large
    desiredCapacity: 1
    volumeSize: 100
    labels:
      nodegroup-type: non-gpu
    ssh:
      publicKeyPath: ~/.ssh/alphadrive-cluster.pub
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        efs: true
  - name: gpu
    amiFamily: Ubuntu2004
    instanceType: g4dn.2xlarge
    desiredCapacity: 0
    minSize: 0
    maxSize: 10
    volumeSize: 200
    labels:
      nodegroup-type: gpu-instances
      autoscaling: enabled
      purpose: gpu-worker
    ssh:
      publicKeyPath: ~/.ssh/alphadrive-cluster.pub
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        efs: true
    ami: ami-00cbcbfa06a1afcce
    preBootstrapCommands:
      - "grep --quiet tsc /sys/devices/system/clocksource/clocksource0/available_clocksource && sudo bash -c 'echo tsc > /sys/devices/system/clocksource/clocksource0/current_clocksource'"
      - "sudo sh -c \"cat /etc/docker/daemon.json | jq '. += {\\\"default-runtime\\\": \\\"nvidia\\\", \\\"runtimes\\\": {\\\"nvidia\\\": {\\\"path\\\": \\\"/usr/bin/nvidia-container-runtime\\\", \\\"runtimeArgs\\\": []}}}' | tee /etc/docker/daemon.json\""
      - "sudo nvidia-xconfig --preserve-busid -a --virtual=1280x1024"
      - "sudo X :0&"
